name: Publish to Rubygem

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true
    - name: build gem
      run: gem build
    - name: publish to Rubygems
      env:
        GEM_HOST_API_KEY: "${{ secrets.RUBYGEMS_API_KEY }}"
      run: gem push boom_nats-*.gem
